### Variables
@baseUrl = http://localhost:3000/api/v1
@accessToken = YourAccessTokenHere

### Basic Search Test 

### Auth Login - Navigate to this in browser to authenticate
GET {{baseUrl}}/auth/login

### Basic Search - Should return Spotify results
GET {{baseUrl}}/spotify/search?q=taylor%20swift
Authorization: Bearer {{accessToken}}


### Search Artists 
GET {{baseUrl}}/spotify/search?q=brian%20adams&type=artist&limit=5
Authorization: Bearer {{accessToken}}

### Search Albums 
GET {{baseUrl}}/spotify/search?q=1989&type=album&limit=5
Authorization: Bearer {{accessToken}}

### Search with All Parameters
GET {{baseUrl}}/spotify/search?q=brian%20adams&type=artist,album,track&limit=10&offset=0
Authorization: Bearer {{accessToken}}


